# Generated by Django 5.1.3 on 2026-07-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="enrollment_date",
            field=models.DateField(blank=True, null=True, verbose_name="تاريخ التسجيل"),
        ),
        migrations.AddField(
            model_name="student",
            name="guardian_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="اسم ولي الأمر"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "نشط"),
                    ("inactive", "موقوف"),
                    ("transferred", "منقول"),
                    ("graduated", "متخرج"),
                ],
                default="active",
                max_length=20,
                verbose_name="حالة الطالب",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
        ),
        migrations.AlterField(
            model_name="student",
            name="address",
            field=models.TextField(blank=True, verbose_name="العنوان"),
        ),
        migrations.AlterField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="student",
            name="father_name",
            field=models.CharField(blank=True, max_length=200, verbose_name="اسم الأب"),
        ),
        migrations.AlterField(
            model_name="student",
            name="fees_paid",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="المدفوع"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="fees_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="الرسوم المستحقة",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="full_name",
            field=models.CharField(max_length=200, verbose_name="الاسم الكامل"),
        ),
        migrations.AlterField(
            model_name="student",
            name="grade",
            field=models.CharField(max_length=100, verbose_name="الصف"),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="رقم الهاتف"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="students/photos/",
                verbose_name="صورة الطالب",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="section",
            field=models.CharField(blank=True, max_length=100, verbose_name="الشعبة"),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_number",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="رقم الطالب"
            ),
        ),
    ]
