# Generated by Django 5.1.3 on 2026-07-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_student_enrollment_date_student_guardian_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="archived_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الأرشفة"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="blood_type",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="فصيلة الدم"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(blank=True, max_length=10, verbose_name="الجنس"),
        ),
        migrations.AddField(
            model_name="student",
            name="last_ministry_sync_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="آخر مزامنة مع الوزارة"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="ministry_student_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="رقم الطالب في الوزارة"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="ministry_sync_status",
            field=models.CharField(
                blank=True,
                default="not_synced",
                max_length=50,
                verbose_name="حالة المزامنة مع الوزارة",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="mother_name",
            field=models.CharField(blank=True, max_length=200, verbose_name="اسم الأم"),
        ),
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "نشط"),
                    ("transferred", "منقول"),
                    ("graduated", "متخرج"),
                    ("archived", "مؤرشف"),
                ],
                default="active",
                max_length=20,
                verbose_name="حالة الطالب",
            ),
        ),
    ]
