# Generated by Django 5.1.3 on 2026-07-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_student_national_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AddField(
            model_name="student",
            name="medical_notes",
            field=models.TextField(blank=True, verbose_name="ملاحظات صحية"),
        ),
    ]
