# Generated by Django 5.2.16 on 2026-07-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_migrate_legacy_finance_and_remove_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='بيانات تجريبية'),
        ),
    ]
