# Generated by Django 6.0.6 on 2026-06-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                ("prefix", models.CharField(max_length=20)),
                ("current_number", models.PositiveIntegerField(default=0)),
                ("padding", models.PositiveIntegerField(default=6)),
                ("yearly_reset", models.BooleanField(default=True)),
            ],
        ),
    ]
