# Generated by Django 5.2.16 on 2026-07-11 18:05

from django.db import migrations, models


def normalize_current_periods(apps, schema_editor):
    AcademicYear = apps.get_model("core", "AcademicYear")
    Semester = apps.get_model("core", "Semester")

    school_ids = AcademicYear.objects.filter(is_current=True).values_list("school_id", flat=True).distinct()
    for school_id in school_ids:
        years = list(AcademicYear.objects.filter(school_id=school_id, is_current=True).order_by("-start_date", "-pk"))
        if len(years) > 1:
            AcademicYear.objects.filter(pk__in=[item.pk for item in years[1:]]).update(is_current=False)

    year_ids = Semester.objects.filter(is_current=True).values_list("academic_year_id", flat=True).distinct()
    for academic_year_id in year_ids:
        semesters = list(Semester.objects.filter(academic_year_id=academic_year_id, is_current=True).order_by("-start_date", "-pk"))
        if len(semesters) > 1:
            Semester.objects.filter(pk__in=[item.pk for item in semesters[1:]]).update(is_current=False)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sequence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['-start_date', 'name']},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['academic_year__start_date', 'start_date']},
        ),
        migrations.RunPython(normalize_current_periods, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('school',), name='one_current_academic_year_per_school'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('academic_year',), name='one_current_semester_per_academic_year'),
        ),
    ]
