# Generated by Django 5.2.16 on 2026-07-13 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_academicyear_options_alter_semester_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataIntegrityRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('scan', 'فحص فقط'), ('fix_safe', 'فحص وإصلاح آمن')], default='scan', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_issues', models.PositiveIntegerField(default=0)),
                ('critical_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('fixed_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrity_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DataIntegrityIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=80)),
                ('severity', models.CharField(choices=[('critical', 'حرج'), ('warning', 'تحذير'), ('info', 'معلومة')], default='warning', max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('object_id', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField()),
                ('is_fixable', models.BooleanField(default=False)),
                ('is_fixed', models.BooleanField(default=False)),
                ('resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='core.dataintegrityrun')),
            ],
            options={
                'ordering': ['severity', 'code', 'id'],
                'indexes': [models.Index(fields=['run', 'severity', 'is_fixed'], name='core_datain_run_id_02a104_idx')],
            },
        ),
    ]
