# Generated by Django 5.2.16 on 2026-07-17 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_unified_two_semesters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإغلاق'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_academic_years', to=settings.AUTH_USER_MODEL, verbose_name='أغلقه'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='closure_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات الإغلاق'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='is_closed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='عام مغلق'),
        ),
    ]
