# Generated by Django 5.x for OPAL ERP V10 Enterprise Foundation
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]
    operations = [
        migrations.CreateModel(
            name="ReportPreset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                ("category", models.CharField(choices=[("students", "الطلاب"), ("finance", "الرسوم والتحصيل"), ("attendance", "الحضور"), ("academic", "الأكاديمي"), ("documents", "الوثائق"), ("operations", "التشغيل")], max_length=30)),
                ("description", models.TextField(blank=True)),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("allowed_roles", models.CharField(blank=True, help_text="Role codes separated by commas", max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["category", "name"]},
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=180)),
                ("message", models.TextField(blank=True)),
                ("level", models.CharField(choices=[("info", "معلومة"), ("success", "نجاح"), ("warning", "تنبيه"), ("danger", "عاجل")], default="info", max_length=20)),
                ("link", models.CharField(blank=True, max_length=500)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("recipient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="opal_notifications", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="WorkflowRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("request_type", models.CharField(choices=[("general", "طلب عام"), ("student", "طلب طالب"), ("parent", "طلب ولي أمر"), ("teacher", "طلب معلم"), ("discount", "طلب خصم"), ("document", "طلب وثيقة"), ("leave", "طلب إجازة"), ("maintenance", "طلب صيانة")], default="general", max_length=30)),
                ("title", models.CharField(max_length=220)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("new", "جديد"), ("review", "قيد المراجعة"), ("approved", "معتمد"), ("rejected", "مرفوض"), ("returned", "معاد للاستكمال"), ("archived", "مؤرشف")], db_index=True, default="new", max_length=20)),
                ("priority", models.CharField(choices=[("low", "منخفضة"), ("normal", "عادية"), ("high", "مرتفعة"), ("urgent", "عاجلة")], db_index=True, default="normal", max_length=20)),
                ("related_app", models.CharField(blank=True, max_length=80)),
                ("related_model", models.CharField(blank=True, max_length=80)),
                ("related_object_id", models.CharField(blank=True, max_length=80)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("assignee", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_workflow_requests", to=settings.AUTH_USER_MODEL)),
                ("branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.branch")),
                ("requester", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="workflow_requests", to=settings.AUTH_USER_MODEL)),
                ("school", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.school")),
            ],
            options={"ordering": ["-created_at"], "permissions": [("approve_workflowrequest", "Can approve workflow request"), ("archive_workflowrequest", "Can archive workflow request")]},
        ),
        migrations.CreateModel(
            name="ApprovalAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(choices=[("submit", "إرسال"), ("review", "بدء المراجعة"), ("approve", "اعتماد"), ("reject", "رفض"), ("return", "إعادة للاستكمال"), ("archive", "أرشفة"), ("comment", "تعليق")], max_length=20)),
                ("note", models.TextField(blank=True)),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("workflow", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="actions", to="enterprise_ops.workflowrequest")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["recipient", "is_read", "-created_at"], name="enterprise__recipie_dcb2f2_idx"),
        ),
    ]
