# Generated by Django 5.2.16 on 2026-07-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_ops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_code', models.CharField(max_length=50)),
                ('feature', models.CharField(choices=[('workflow', 'الطلبات وسير العمل'), ('approvals', 'الموافقات'), ('notifications', 'الإشعارات'), ('audit', 'سجل العمليات'), ('reports', 'التقارير'), ('executive', 'اللوحة التنفيذية')], max_length=30)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['role_code', 'feature'],
                'unique_together': {('role_code', 'feature')},
            },
        ),
    ]
