# Generated by Django 5.2.16 on 2026-07-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_ops', '0002_rolepermissionrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermissionrule',
            name='feature',
            field=models.CharField(choices=[('workflow', 'الطلبات وسير العمل'), ('approvals', 'الموافقات'), ('notifications', 'الإشعارات'), ('audit', 'سجل العمليات'), ('reports', 'التقارير'), ('executive', 'اللوحة التنفيذية'), ('students', 'إدارة الطلاب'), ('academics', 'الشؤون الأكاديمية'), ('attendance', 'الحضور'), ('exams', 'الامتحانات'), ('finance', 'الرسوم المدرسية'), ('documents', 'الوثائق'), ('timetable', 'الجدول الدراسي')], max_length=30),
        ),
        migrations.AlterField(
            model_name='workflowrequest',
            name='request_type',
            field=models.CharField(choices=[('general', 'طلب عام'), ('student', 'طلب طالب'), ('parent', 'طلب ولي أمر'), ('teacher', 'طلب معلم'), ('discount', 'طلب خصم'), ('document', 'طلب وثيقة'), ('leave', 'طلب إجازة'), ('maintenance', 'طلب صيانة'), ('transfer', 'طلب نقل طالب'), ('withdrawal', 'طلب انسحاب طالب'), ('reenrollment', 'طلب إعادة قيد'), ('payment_correction', 'طلب تصحيح دفعة'), ('mark_change', 'طلب تعديل نتيجة')], default='general', max_length=30),
        ),
    ]
