# Generated by Django 5.2.16 on 2026-07-18 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_ops', '0003_alter_rolepermissionrule_feature_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event_key',
            field=models.CharField(blank=True, db_index=True, max_length=180),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('event_key', ''), _negated=True), fields=('recipient', 'event_key'), name='uniq_notification_recipient_event'),
        ),
    ]
