# Generated by Django 5.2.16 on 2026-07-19 00:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_dataintegrityrun_school'),
        ('enterprise_ops', '0004_notification_event_key_and_more'),
        ('teachers', '0009_alter_teacher_is_demo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sound_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reportpreset',
            name='category',
            field=models.CharField(choices=[('students', 'الطلاب'), ('finance', 'الرسوم والتحصيل'), ('attendance', 'الحضور'), ('academic', 'الأكاديمي'), ('documents', 'الوثائق'), ('operations', 'العمليات')], max_length=30),
        ),
        migrations.AlterField(
            model_name='rolepermissionrule',
            name='feature',
            field=models.CharField(choices=[('workflow', 'الشكاوى والاقتراحات'), ('approvals', 'التعاميم والتنبيهات'), ('notifications', 'الإشعارات'), ('audit', 'سجل العمليات'), ('reports', 'التقارير'), ('executive', 'لوحة الإدارة'), ('students', 'إدارة الطلاب'), ('academics', 'الشؤون الأكاديمية'), ('attendance', 'الحضور'), ('exams', 'الامتحانات'), ('finance', 'الرسوم المدرسية'), ('documents', 'الوثائق'), ('timetable', 'الجدول الدراسي')], max_length=30),
        ),
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('circular', 'تعميم'), ('teacher_alert', 'تنبيه لمعلم محدد')], default='circular', max_length=30)),
                ('audience', models.CharField(choices=[('teachers', 'المعلمون'), ('parents', 'أولياء الأمور'), ('all', 'الجميع')], default='all', max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('recipients_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_broadcast_messages', to=settings.AUTH_USER_MODEL)),
                ('specific_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_alerts', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('complaint', 'شكوى'), ('suggestion', 'اقتراح')], max_length=20)),
                ('title', models.CharField(max_length=220)),
                ('message', models.TextField()),
                ('teaching_quality_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='تقييم جودة التدريس')),
                ('electronic_services_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='تقييم الخدمات الإلكترونية')),
                ('status', models.CharField(choices=[('new', 'جديدة'), ('review', 'قيد المراجعة'), ('resolved', 'تمت المعالجة'), ('closed', 'مغلقة')], db_index=True, default='new', max_length=20)),
                ('response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_feedback_tickets', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_tickets', to='core.branch')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_tickets', to='core.school')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='feedback_status_created_idx'), models.Index(fields=['sender', '-created_at'], name='feedback_sender_created_idx')],
            },
        ),
    ]
