# Generated by Django 5.2.16 on 2026-07-26 01:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_semester_structure_snapshot'),
        ('enterprise_ops', '0005_notification_sound_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackticket',
            name='electronic_services_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='حقل تاريخي محفوظ للرسائل القديمة فقط؛ لا يُستخدم للتقييمات الجديدة.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='تقييم الخدمات الإلكترونية'),
        ),
        migrations.AlterField(
            model_name='feedbackticket',
            name='teaching_quality_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='حقل تاريخي محفوظ للرسائل القديمة فقط؛ لا يُستخدم للتقييمات الجديدة.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='تقييم جودة التدريس'),
        ),
        migrations.CreateModel(
            name='MonthlyServiceEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(db_index=True, help_text='يحفظ اليوم الأول من الشهر.', verbose_name='شهر التقييم')),
                ('electronic_services_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='تقييم الخدمات الإلكترونية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_service_evaluations', to='core.branch')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_service_evaluations', to='core.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_service_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تقييم شهري للخدمات الإلكترونية',
                'verbose_name_plural': 'التقييمات الشهرية للخدمات الإلكترونية',
                'ordering': ['-period', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'period'), name='uniq_user_monthly_service_evaluation')],
            },
        ),
    ]
