# Generated by Django 5.2.16 on 2026-07-26 02:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_ops', '0006_alter_feedbackticket_electronic_services_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyserviceevaluation',
            options={'ordering': ['-period', '-created_at'], 'verbose_name': 'تقييم شهري لرضا المدرسة', 'verbose_name_plural': 'التقييمات الشهرية لرضا المدرسة'},
        ),
        migrations.AddField(
            model_name='monthlyserviceevaluation',
            name='teaching_quality_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='إلزامي لولي الأمر فقط؛ المعلم لا يقيّم جودة تدريسه.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='تقييم جودة التدريس'),
        ),
    ]
