# Generated by Django 5.2.16 on 2026-07-26 02:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_ops', '0007_alter_monthlyserviceevaluation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyserviceevaluation',
            name='electronic_services_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyserviceevaluation',
            name='teaching_quality_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyserviceevaluation',
            name='electronic_services_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='إلزامي في تقييم الخدمات الإلكترونية المستقل.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='تقييم الخدمات الإلكترونية'),
        ),
    ]
