# Generated by Django 6.0.6 on 2026-06-26 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0002_guardian_studentdocument_studentguardian"),
        ("core", "0002_sequence"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("application_number", models.CharField(max_length=50, unique=True)),
                ("student_full_name", models.CharField(max_length=200)),
                ("father_name", models.CharField(blank=True, max_length=200)),
                ("mother_name", models.CharField(blank=True, max_length=200)),
                ("gender", models.CharField(blank=True, max_length=10)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("address", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="admissions/photos/"
                    ),
                ),
                ("guardian_name", models.CharField(max_length=200)),
                ("guardian_phone", models.CharField(max_length=30)),
                ("guardian_email", models.EmailField(blank=True, max_length=254)),
                ("guardian_job", models.CharField(blank=True, max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("submitted", "مقدم"),
                            ("under_review", "قيد المراجعة"),
                            ("approved", "مقبول"),
                            ("rejected", "مرفوض"),
                            ("converted", "تم تحويله لطالب"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.academicyear",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.branch",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academics.grade",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.school"
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academics.section",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
