# Generated by Django 5.2.16 on 2026-07-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_fee_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='guardian_national_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='الرقم الوطني لولي الأمر'),
        ),
    ]
