# Generated by Django 5.2.16 on 2026-07-18 18:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_fee_payment_tokens(apps, schema_editor):
    FeePayment = apps.get_model('admissions', 'FeePayment')
    for pk in FeePayment.objects.filter(operation_token__isnull=True).values_list('pk', flat=True).iterator():
        FeePayment.objects.filter(pk=pk).update(operation_token=uuid.uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_guardian_terminology'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_fee_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='deletion_reason',
            field=models.TextField(blank=True, verbose_name='سبب الحذف'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='محذوف بأمان'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='operation_token',
            field=models.UUIDField(editable=False, null=True, verbose_name='معرف العملية'),
        ),
        migrations.RunPython(populate_fee_payment_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='feepayment',
            name='operation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='معرف العملية'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('card', 'بطاقة بنكية'), ('bank_transfer', 'تحويل بنكي'), ('online', 'دفع إلكتروني'), ('cheque', 'شيك'), ('unspecified', 'غير محدد (سجل سابق)')], default='unspecified', max_length=30, verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('card', 'بطاقة بنكية'), ('bank_transfer', 'تحويل بنكي'), ('online', 'دفع إلكتروني'), ('cheque', 'شيك'), ('unspecified', 'غير محدد (سجل سابق)')], default='unspecified', max_length=30, verbose_name='طريقة الدفع'),
        ),
    ]
