# Generated by Django 5.2.16 on 2026-07-18 18:58

import uuid
from django.db import migrations, models


def populate_registration_tokens(apps, schema_editor):
    StudentRegistration = apps.get_model('admissions', 'StudentRegistration')
    for pk in StudentRegistration.objects.filter(operation_token__isnull=True).values_list('pk', flat=True).iterator():
        StudentRegistration.objects.filter(pk=pk).update(operation_token=uuid.uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_feepayment_deleted_at_feepayment_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='operation_token',
            field=models.UUIDField(editable=False, null=True, verbose_name='معرف عملية التسجيل'),
        ),
        migrations.RunPython(populate_registration_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='studentregistration',
            name='operation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='معرف عملية التسجيل'),
        ),
    ]
