# Generated by Django 5.2.16 on 2026-07-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0009_studentregistration_operation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionapplication',
            name='status',
            field=models.CharField(choices=[('candidate', 'مرشح للقبول'), ('draft', 'مسودة'), ('submitted', 'مقدم'), ('under_review', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض'), ('converted', 'تم تحويله لطالب')], default='draft', max_length=30),
        ),
    ]
