# Generated by Django 5.2.16 on 2026-09-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_dashboard_layout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="code",
            field=models.CharField(
                choices=[
                    ("super_admin", "مدير النظام"),
                    ("school_owner", "مالك المدرسة"),
                    ("principal", "مدير المدرسة"),
                    ("accountant", "محاسب"),
                    ("secretary", "سكرتير"),
                    ("teacher", "معلم"),
                    ("student", "طالب مدرسة"),
                    ("parent", "ولي أمر"),
                    ("academy_student", "طالب أكاديمية"),
                    ("guest", "زائر"),
                    ("driver", "سائق"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
