# Generated by Django 5.2.16 on 2026-08-04 08:48

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='اسم المادة')),
                ('slug', models.SlugField(allow_unicode=True, max_length=140, unique=True, verbose_name='المعرف')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LearningAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='رقم الهاتف')),
                ('role', models.CharField(choices=[('learner', 'متعلم'), ('teacher', 'مدرّس'), ('manager', 'مدير المنصة')], default='learner', max_length=20, verbose_name='نوع الحساب')),
                ('password', models.CharField(editable=False, max_length=128, verbose_name='كلمة المرور المشفرة')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر دخول')),
            ],
            options={
                'ordering': ['full_name', 'id'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='uniq_learning_account_email_ci')],
            },
        ),
        migrations.CreateModel(
            name='LearningAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('registered', 'تسجيل حساب'), ('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('subscription_activated', 'تفعيل اشتراك')], db_index=True, max_length=40)),
                ('entity_type', models.CharField(blank=True, max_length=60)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='learning_platform.learningaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='عنوان الدورة')),
                ('slug', models.SlugField(allow_unicode=True, max_length=240, unique=True, verbose_name='المعرف')),
                ('summary', models.TextField(blank=True, verbose_name='الملخص')),
                ('grade_label', models.CharField(blank=True, max_length=120, verbose_name='المستوى أو الصف')),
                ('cover_color', models.CharField(default='#7254d8', max_length=20, verbose_name='لون الغلاف')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشورة'), ('archived', 'مؤرشفة')], db_index=True, default='draft', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_courses', to='learning_platform.learningaccount', verbose_name='المدرّس')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='learning_platform.learningsubject', verbose_name='المادة')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningSubscriptionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='رمز البطاقة')),
                ('duration', models.CharField(choices=[('monthly', 'شهري'), ('termly', 'فصلي'), ('yearly', 'سنوي')], max_length=20, verbose_name='المدة')),
                ('grants_all_subjects', models.BooleanField(default=False, verbose_name='جميع المواد')),
                ('status', models.CharField(choices=[('available', 'متاحة'), ('redeemed', 'مفعلة'), ('cancelled', 'ملغاة')], db_index=True, default='available', max_length=20, verbose_name='الحالة')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_cards', to='learning_platform.learningaccount')),
                ('subjects', models.ManyToManyField(blank=True, related_name='subscription_cards', to='learning_platform.learningsubject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], db_index=True, default='active', max_length=20)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, verbose_name='نسبة الإنجاز')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='learning_platform.learningcourse')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='learning_platform.learningaccount')),
            ],
            options={
                'ordering': ['-last_activity_at', '-enrolled_at'],
                'constraints': [models.UniqueConstraint(fields=('learner', 'course'), name='uniq_learning_enrollment'), models.CheckConstraint(condition=models.Q(('progress_percent__gte', 0), ('progress_percent__lte', 100)), name='learning_progress_between_0_100')],
            },
        ),
        migrations.CreateModel(
            name='LearningLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='عنوان الدرس')),
                ('slug', models.SlugField(allow_unicode=True, max_length=240, verbose_name='المعرف')),
                ('content', models.TextField(blank=True, verbose_name='المحتوى')),
                ('video_url', models.URLField(blank=True, verbose_name='رابط الفيديو')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='المدة بالدقائق')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='الترتيب')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='منشور')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning_platform.learningcourse')),
            ],
            options={
                'ordering': ['course_id', 'order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('course', 'slug'), name='uniq_learning_lesson_slug'), models.UniqueConstraint(fields=('course', 'order'), name='uniq_learning_lesson_order')],
            },
        ),
    ]
