# Generated by Django 5.1.3 on 2026-06-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("version", models.CharField(blank=True, max_length=20)),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("priority", models.PositiveSmallIntegerField(default=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "مخطط لها"),
                            ("development", "قيد التطوير"),
                            ("completed", "مكتملة"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["priority", "name"],
            },
        ),
    ]
