# Generated by Django 5.1.3 on 2026-06-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("development_center", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="module",
            options={
                "ordering": ["priority", "name"],
                "verbose_name": "وحدة تطوير",
                "verbose_name_plural": "وحدات التطوير",
            },
        ),
        migrations.AddField(
            model_name="module",
            name="category",
            field=models.CharField(blank=True, max_length=100, verbose_name="التصنيف"),
        ),
        migrations.AlterField(
            model_name="module",
            name="description",
            field=models.TextField(blank=True, verbose_name="الوصف"),
        ),
        migrations.AlterField(
            model_name="module",
            name="name",
            field=models.CharField(max_length=120, verbose_name="اسم الوحدة"),
        ),
        migrations.AlterField(
            model_name="module",
            name="priority",
            field=models.PositiveSmallIntegerField(default=3, verbose_name="الأولوية"),
        ),
        migrations.AlterField(
            model_name="module",
            name="progress",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="نسبة الإنجاز"
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "🔴 مخطط لها"),
                    ("development", "🟡 قيد التطوير"),
                    ("completed", "🟢 مكتملة"),
                ],
                default="planned",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="version",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="الإصدار المستهدف"
            ),
        ),
    ]
