# Generated by Django 5.1.3 on 2026-06-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("development_center", "0003_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=30, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("planned_date", models.DateField(blank=True, null=True)),
                ("released", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-planned_date", "-id"],
            },
        ),
    ]
