# Generated by Django 5.1.3 on 2026-06-28 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("development_center", "0004_release"),
    ]

    operations = [
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="development_center.release",
                    ),
                ),
            ],
            options={
                "ordering": ["target_date", "title"],
            },
        ),
    ]
