# Generated by Django 5.1.3 on 2026-06-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("development_center", "0005_milestone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Idea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("priority", models.PositiveSmallIntegerField(default=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جديدة"),
                            ("study", "قيد الدراسة"),
                            ("approved", "معتمدة"),
                            ("implemented", "تم تنفيذها"),
                            ("rejected", "مرفوضة"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["priority", "-created_at"],
            },
        ),
    ]
