# Generated by Django 5.1.3 on 2026-06-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("development_center", "0006_idea"),
    ]

    operations = [
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("decision", models.TextField()),
                ("reason", models.TextField(blank=True)),
                ("impact", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "مقترح"),
                            ("approved", "معتمد"),
                            ("deprecated", "ملغي"),
                        ],
                        default="approved",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
