# Generated by Django 5.1.3 on 2026-06-29 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("development_center", "0008_bug"),
    ]

    operations = [
        migrations.AddField(
            model_name="bug",
            name="release",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="release_bugs",
                to="development_center.release",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="release",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="development_center.release",
            ),
        ),
    ]
