# Generated by Django 5.2.15 on 2026-06-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("development_center", "0011_activitylog_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="depends_on",
            field=models.ManyToManyField(
                blank=True,
                related_name="blocked_tasks",
                to="development_center.task",
                verbose_name="يعتمد على",
            ),
        ),
    ]
