# Generated by Django 5.2.15 on 2026-06-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("development_center", "0012_task_depends_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="تاريخ النهاية"),
        ),
        migrations.AddField(
            model_name="task",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="تاريخ البداية"),
        ),
    ]
