# Generated by Django 5.2.15 on 2026-06-30 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("development_center", "0013_task_due_date_task_start_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="اسم السبرنت")),
                ("goal", models.TextField(blank=True, verbose_name="هدف السبرنت")),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ البداية"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ النهاية"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "مخطط"),
                            ("active", "نشط"),
                            ("completed", "مكتمل"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-start_date", "-id"],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="development_center.sprint",
                verbose_name="السبرنت",
            ),
        ),
    ]
