# Generated by Django 5.2.15 on 2026-06-30 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("development_center", "0014_sprint_task_sprint"),
    ]

    operations = [
        migrations.CreateModel(
            name="SprintDailySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_tasks", models.PositiveIntegerField(default=0)),
                ("remaining_tasks", models.PositiveIntegerField(default=0)),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="development_center.sprint",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("sprint", "date")},
            },
        ),
    ]
