# Generated by Django 5.1.3 on 2026-07-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("development_center", "0016_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="ترتيب التنفيذ"),
        ),
    ]
