# Generated by Django 5.1.3 on 2026-06-28 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0006_section_academic_year"),
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="academics.subject"
            ),
        ),
    ]
