# Generated by Django 5.2.16 on 2026-07-11 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_alter_enrollment_status'),
        ('core', '0002_sequence'),
        ('exams', '0003_alter_studentmark_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='pass_percentage',
            field=models.DecimalField(decimal_places=2, default=60, max_digits=5),
        ),
        migrations.AddField(
            model_name='exam',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='core.semester'),
        ),
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('open', 'مفتوح لإدخال العلامات'), ('approved', 'معتمد'), ('published', 'منشور'), ('closed', 'مغلق')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='وزن الامتحان'),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_marks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_marks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('monthly', 'امتحان شهري'), ('midterm', 'نصف الفصل'), ('final', 'نهائي'), ('quiz', 'اختبار قصير'), ('coursework', 'أعمال سنة')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['academic_year', 'grade', 'status'], name='exams_exam_academi_820904_idx'),
        ),
    ]
