# Generated by Django 5.2.16 on 2026-07-19 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_archive_duplicate_grades'),
        ('core', '0008_dataintegrityrun_school'),
        ('exams', '0005_unified_four_assessments'),
        ('teachers', '0009_alter_teacher_is_demo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['academic_year', 'semester__code', 'grade__order', 'section__name', 'subject__name', 'exam_type']},
        ),
        migrations.RemoveConstraint(
            model_name='exam',
            name='uniq_four_assessments_per_subject_term',
        ),
        migrations.AddField(
            model_name='exam',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='academics.section', verbose_name='الشعبة'),
        ),
        migrations.AddField(
            model_name='exam',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال للمراجعة'),
        ),
        migrations.AddField(
            model_name='exam',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_exams', to=settings.AUTH_USER_MODEL, verbose_name='أرسله للمراجعة'),
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='teachers.teacherassignment', verbose_name='تكليف المعلم'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('open', 'مفتوح لإدخال العلامات'), ('submitted', 'مرسل للإدارة للمراجعة'), ('approved', 'معتمد'), ('published', 'منشور'), ('closed', 'مغلق')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(condition=models.Q(('section__isnull', False)), fields=('academic_year', 'semester', 'section', 'subject', 'exam_type'), name='uniq_section_assessment_per_subject_term'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(condition=models.Q(('section__isnull', True)), fields=('academic_year', 'semester', 'grade', 'subject', 'exam_type'), name='uniq_legacy_assessment_per_subject_term'),
        ),
    ]
