# Generated by Django 5.2.16 on 2026-07-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_exam_cycles_and_result_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='marks_due_date',
            field=models.DateField(blank=True, help_text='الموعد المعتمد لقياس إدخال العلامات ضمن الوقت في مؤشر TPI.', null=True, verbose_name='الموعد النهائي لإدخال العلامات'),
        ),
    ]
