# Generated by Django 5.2.16 on 2026-07-13 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_teacherassignment_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='بيانات تجريبية'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الراتب الشهري'),
        ),
        migrations.CreateModel(
            name='TeacherDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('contract', 'عقد عمل'), ('qualification', 'مؤهل علمي'), ('identity', 'هوية'), ('experience', 'شهادة خبرة'), ('other', 'أخرى')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('document_number', models.CharField(blank=True, max_length=80)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, upload_to='teachers/documents/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
