# Generated by Django 5.2.16 on 2026-07-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انفكاك المعلم'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='end_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='سبب الانفكاك'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='weekly_periods',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='عدد الحصص أسبوعيًا'),
        ),
    ]
