# Generated by Django 5.2.16 on 2026-07-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_teacher_end_date_teacher_end_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='بيانات مُدخلة آليًا (توافق سابق)'),
        ),
    ]
