# Generated by Django 5.2.16 on 2026-07-25 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_semester_structure_snapshot'),
        ('teachers', '0011_teacher_photo_size_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(db_index=True, verbose_name='شهر المؤشر')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='نقاط TPI')),
                ('evidence_coverage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='تغطية الأدلة')),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='الترتيب')),
                ('components', models.JSONField(blank=True, default=dict, verbose_name='تفاصيل المؤشرات')),
                ('improvement_actions', models.JSONField(blank=True, default=list, verbose_name='مؤشرات التحسين')),
                ('calculation_version', models.CharField(default='TPI-107', max_length=30)),
                ('is_closed', models.BooleanField(db_index=True, default=False, verbose_name='نتيجة شهرية مغلقة')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_tpi_snapshots', to='core.academicyear', verbose_name='العام الدراسي')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tpi_snapshots', to='teachers.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'لقطة مؤشر أداء المعلم',
                'verbose_name_plural': 'لقطات مؤشر أداء المعلمين',
                'ordering': ['-period', 'rank', 'teacher__full_name'],
                'indexes': [models.Index(fields=['period', 'is_closed', 'score'], name='teacher_tpi_period_score_idx')],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'period'), name='uniq_teacher_tpi_snapshot_period')],
            },
        ),
    ]
