# Generated by Django 6.0.6 on 2026-06-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("student_certificate", "إثبات طالب"),
                            ("student_status", "شهادة قيد"),
                            ("transfer_letter", "كتاب انتقال"),
                            ("acceptance_letter", "كتاب قبول"),
                            ("initial_acceptance", "كتاب قبول مبدئي"),
                            ("clearance", "براءة ذمة"),
                            ("report_card", "كشف علامات"),
                            ("custom", "وثيقة مخصصة"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("body", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
