# Generated by Django 5.1.3 on 2026-07-04 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_studentissueddocument"),
        ("students", "0004_student_national_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issueddocument",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="students.student",
            ),
        ),
        migrations.AlterField(
            model_name="studentissueddocument",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issued_documents",
                to="students.student",
            ),
        ),
    ]
