# Generated by Django 5.2.16 on 2026-07-11 18:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_verification_codes(apps, schema_editor):
    IssuedDocument = apps.get_model("documents", "IssuedDocument")
    for document in IssuedDocument.objects.filter(verification_code__isnull=True).iterator():
        document.verification_code = uuid.uuid4()
        document.save(update_fields=["verification_code"])


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_issueddocument_student_and_more'),
        ('students', '0005_student_is_active_student_medical_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issueddocument',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='issueddocument',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issueddocument',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issueddocument',
            name='replaces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_documents', to='documents.issueddocument'),
        ),
        migrations.AddField(
            model_name='issueddocument',
            name='status',
            field=models.CharField(choices=[('active', 'فعّالة'), ('cancelled', 'ملغاة')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='issueddocument',
            name='verification_code',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(populate_verification_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='issueddocument',
            name='verification_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='issueddocument',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='studentissueddocument',
            unique_together={('student', 'issued_document')},
        ),
    ]
