# Generated by Django 5.2.16 on 2026-07-18 20:33

import django.db.models.deletion
import documents.models
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_codes_and_defaults(apps, schema_editor):
    DocumentTemplate = apps.get_model('documents', 'DocumentTemplate')
    for item in DocumentTemplate.objects.filter(code__isnull=True):
        item.code = f"legacy-{item.pk}-{uuid.uuid4().hex[:10]}"
        item.save(update_fields=['code'])
    from documents.defaults import DEFAULT_DOCUMENT_TEMPLATES
    for definition in DEFAULT_DOCUMENT_TEMPLATES:
        DocumentTemplate.objects.update_or_create(
            code=definition['code'],
            defaults={
                'name': definition['name'], 'audience': definition['audience'],
                'document_type': definition['document_type'], 'title': definition['title'],
                'body': definition['body'], 'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0010_alter_admissionapplication_status'),
        ('core', '0008_dataintegrityrun_school'),
        ('documents', '0005_issueddocument_cancellation_reason_and_more'),
        ('parent_portal', '0010_family_merged_into'),
        ('teachers', '0008_teacher_end_date_teacher_end_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='audience',
            field=models.CharField(choices=[('student', 'الطالب'), ('candidate', 'المرشح للقبول'), ('teacher', 'المعلم'), ('guardian', 'ولي الأمر')], db_index=True, default='student', max_length=20),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='code',
            field=models.SlugField(blank=True, editable=False, max_length=80, null=True),
        ),
        migrations.RunPython(populate_codes_and_defaults, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='documenttemplate',
            name='code',
            field=models.SlugField(default=documents.models.new_template_code, editable=False, max_length=80, unique=True),
        ),
        migrations.AddField(
            model_name='issueddocument',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_documents', to='admissions.admissionapplication'),
        ),
        migrations.AddField(
            model_name='issueddocument',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_documents', to='parent_portal.family'),
        ),
        migrations.AddField(
            model_name='issueddocument',
            name='manager_name_snapshot',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='issueddocument',
            name='manager_title_snapshot',
            field=models.CharField(blank=True, default='المدير العام', max_length=120),
        ),
        migrations.AddField(
            model_name='issueddocument',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='issueddocument',
            name='stamp_label_snapshot',
            field=models.CharField(blank=True, default='ختم المدرسة', max_length=120),
        ),
        migrations.AddField(
            model_name='issueddocument',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_documents', to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='document_type',
            field=models.CharField(choices=[('student_certificate', 'إثبات طالب'), ('student_status', 'شهادة قيد'), ('transfer_letter', 'كتاب انتقال'), ('acceptance_letter', 'كتاب قبول'), ('initial_acceptance', 'كتاب قبول مبدئي'), ('clearance', 'براءة ذمة'), ('report_card', 'كشف علامات'), ('custom', 'وثيقة مخصصة'), ('teacher_experience', 'شهادة خبرة'), ('teacher_appreciation', 'شهادة تقدير'), ('teacher_recommendation', 'كتاب توصية'), ('teacher_salary', 'تعريف راتب'), ('guardian_statement', 'كشف حساب ولي الأمر'), ('student_conduct', 'شهادة حسن سيرة وسلوك')], max_length=50),
        ),
        migrations.CreateModel(
            name='DocumentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(blank=True, max_length=200, verbose_name='اسم المدير العام')),
                ('manager_title', models.CharField(default='المدير العام', max_length=120, verbose_name='المسمى الوظيفي')),
                ('stamp_label', models.CharField(default='ختم المدرسة', max_length=120, verbose_name='عبارة الختم')),
                ('footer_text', models.CharField(blank=True, max_length=250, verbose_name='تذييل الوثائق')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_settings', to='core.school')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
