# Generated by Django 5.1.3 on 2026-07-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_student_archived_at_student_blood_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="national_id",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="الرقم الوطني"
            ),
        ),
    ]
