# Generated by Django 5.1.3 on 2026-07-04 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parent_portal", "0003_notification"),
        ("students", "0004_student_national_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="students.student",
            ),
        ),
        migrations.AlterField(
            model_name="parentmessage",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="students.student"
            ),
        ),
        migrations.AlterField(
            model_name="parentprofile",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parents",
                to="students.student",
            ),
        ),
    ]
