# Generated by Django 5.1.3 on 2026-07-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parent_portal", "0005_family_parent_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="family_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, verbose_name="رمز العائلة"
            ),
        ),
        migrations.AddField(
            model_name="family",
            name="guardian_national_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                verbose_name="الرقم الوطني لولي الأمر",
            ),
        ),
    ]
