# Generated by Django 5.2.16 on 2026-07-18 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent_portal', '0009_guardian_terminology'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_records', to='parent_portal.family', verbose_name='مُدمج في ملف ولي الأمر'),
        ),
    ]
