# Generated by Django 5.2.16 on 2026-07-26 01:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent_portal', '0012_teacher_monthly_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermonthlyevaluation',
            name='electronic_services_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='للتوافق مع التقييمات السابقة فقط؛ التقييم الحالي للخدمات الإلكترونية مركزي ومستقل.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='الخدمات الإلكترونية (سجل تاريخي)'),
        ),
    ]
