# Generated by Django 5.2.16 on 2026-07-11 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_alter_enrollment_status'),
        ('core', '0002_sequence'),
        ('teachers', '0004_alter_teacherassignment_academic_year'),
        ('timetable', '0002_alter_timetableentry_academic_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetableentry',
            options={'ordering': ['day', 'time_slot__order', 'section__grade__order', 'section__name']},
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.section'),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetable.timeslot'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['academic_year', 'day'], name='timetable_t_academi_c057ed_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['teacher', 'day'], name='timetable_t_teacher_da3f29_idx'),
        ),
    ]
