# Generated by Django 5.2.16 on 2026-07-18 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_dataintegrityrun_school'),
        ('teachers', '0008_teacher_end_date_teacher_end_reason_and_more'),
        ('timetable', '0003_alter_timetableentry_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='generated_automatically',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='day',
            field=models.CharField(choices=[('saturday', 'السبت'), ('sunday', 'الأحد'), ('monday', 'الاثنين'), ('tuesday', 'الثلاثاء'), ('wednesday', 'الأربعاء'), ('thursday', 'الخميس'), ('friday', 'الجمعة')], max_length=20),
        ),
        migrations.CreateModel(
            name='SchoolDayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='اسم الحدث')),
                ('event_type', models.CharField(choices=[('assembly', 'طابور صباحي'), ('break', 'استراحة'), ('dismissal', 'نهاية دوام'), ('other', 'حدث آخر')], default='other', max_length=20, verbose_name='نوع الحدث')),
                ('start_time', models.TimeField(verbose_name='وقت البداية')),
                ('end_time', models.TimeField(verbose_name='وقت النهاية')),
                ('days', models.CharField(default='saturday,sunday,monday,tuesday,wednesday', max_length=120, verbose_name='أيام التطبيق')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_events', to='core.school')),
            ],
            options={
                'ordering': ['order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='SchoolScheduleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekend_days', models.CharField(default='thursday,friday', max_length=100, verbose_name='أيام العطلة')),
                ('alert_minutes_before_end', models.PositiveSmallIntegerField(default=5, verbose_name='التنبيه قبل نهاية الحدث بالدقائق')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_settings', to='core.school')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('needed', 'بحاجة إشغال'), ('assigned', 'تم تعيين بديل'), ('cancelled', 'ملغاة')], db_index=True, default='needed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_records', to='timetable.timetableentry')),
                ('substitute_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_coverages', to='teachers.teacher')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('entry', 'date'), name='uniq_entry_coverage_date')],
            },
        ),
        migrations.CreateModel(
            name='TeacherAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_absences', to='teachers.teacher')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('teacher', 'date'), name='uniq_teacher_absence_date')],
            },
        ),
    ]
