# Generated by Django 5.2.16 on 2026-07-25 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_legacy_teacher_absence_meaning(apps, schema_editor):
    """Map existing absence rows without deleting or reinterpreting data.

    Historic ``excused`` records are the authorised exception equivalent;
    historic ``unexcused`` records remain an absence that affects TPI.
    """
    TeacherAbsence = apps.get_model("timetable", "TeacherAbsence")
    TeacherAbsence.objects.filter(absence_type="excused").update(
        attendance_status="approved_excuse",
        is_approved=True,
    )
    TeacherAbsence.objects.filter(absence_type="unexcused").update(
        attendance_status="absent",
        is_approved=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_teacher_absence_payroll_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherabsence',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_teacher_work_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherabsence',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت القدوم'),
        ),
        migrations.AddField(
            model_name='teacherabsence',
            name='attendance_status',
            field=models.CharField(choices=[('present', 'منتظم'), ('late', 'متأخر'), ('early_departure', 'مغادرة مبكرة'), ('absent', 'غائب'), ('approved_excuse', 'عذر معتمد'), ('official_mission', 'مهمة رسمية')], db_index=True, default='absent', max_length=30, verbose_name='حالة الدوام'),
        ),
        migrations.AddField(
            model_name='teacherabsence',
            name='departure_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت المغادرة'),
        ),
        migrations.AddField(
            model_name='teacherabsence',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False, verbose_name='استثناء معتمد'),
        ),
        migrations.RunPython(
            preserve_legacy_teacher_absence_meaning,
            migrations.RunPython.noop,
        ),
    ]
