# Generated by Django 5.1.3 on 2026-06-28 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0006_section_academic_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curriculum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weekly_periods", models.PositiveIntegerField(default=1)),
                ("is_required", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculums",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculums",
                        to="academics.grade",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculums",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "خطة دراسية",
                "verbose_name_plural": "الخطط الدراسية",
                "ordering": ["academic_year", "grade", "subject"],
                "unique_together": {("academic_year", "grade", "subject")},
            },
        ),
    ]
