# Generated by Django 6.0.6 on 2026-06-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_guardian_studentdocument_studentguardian"),
    ]

    operations = [
        migrations.AddField(
            model_name="guardian",
            name="medical_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentrecord",
            name="blood_type",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="studentrecord",
            name="medical_notes",
            field=models.TextField(blank=True),
        ),
    ]
