# Generated by Django 6.0.6 on 2026-06-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_guardian_medical_notes_studentrecord_blood_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentrecord",
            name="national_id",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
