# Generated by Django 5.1.3 on 2026-06-28 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_academicyear_alter_subject_options_and_more"),
        ("core", "0002_sequence"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sections",
                to="core.academicyear",
            ),
        ),
    ]
