# Generated by Django 5.1.3 on 2026-06-28 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0006_section_academic_year"),
        ("core", "0002_sequence"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("academic_year", "branch", "grade", "name")},
        ),
    ]
