# Generated by Django 5.1.3 on 2026-07-04 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0007_alter_section_unique_together"),
        ("students", "0005_student_is_active_student_medical_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdocument",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="students.student",
            ),
        ),
        migrations.AlterField(
            model_name="studentguardian",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guardians",
                to="students.student",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="students.student",
            ),
        ),
        migrations.DeleteModel(
            name="StudentRecord",
        ),
    ]
