# Generated by Django 5.1.3 on 2026-07-04 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    # IMPORTANT: the legacy apps originally created foreign keys to
    # academics.StudentRecord.  They must migrate those foreign keys to the
    # canonical students.Student model before StudentRecord is removed.
    # Keeping this ordering in the historical graph allows a brand-new
    # database to migrate cleanly while remaining safe for existing installs
    # where these migrations are already recorded as applied.
    dependencies = [
        ("academics", "0007_alter_section_unique_together"),
        ("students", "0005_student_is_active_student_medical_notes"),
        ("accounting", "0004_alter_studentinvoice_student"),
        ("attendance_v2", "0002_alter_attendance_student"),
        ("documents", "0004_alter_issueddocument_student_and_more"),
        ("exams", "0003_alter_studentmark_student"),
        ("parent_portal", "0004_alter_notification_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdocument",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="students.student",
            ),
        ),
        migrations.AlterField(
            model_name="studentguardian",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guardians",
                to="students.student",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="students.student",
            ),
        ),
        migrations.DeleteModel(
            name="StudentRecord",
        ),
    ]
