# Generated by Django 5.2.16 on 2026-07-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_studentdocument_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('promote', 'ترفيع'), ('transfer', 'نقل'), ('withdraw', 'انسحاب'), ('reenroll', 'إعادة قيد'), ('graduate', 'تخريج'), ('section_change', 'تغيير شعبة')], max_length=30)),
                ('effective_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
