# Generated by Django 5.2.16 on 2026-07-11 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_studentlifecycleevent'),
        ('curriculum', '0002_alter_curriculum_academic_year'),
        ('students', '0005_student_is_active_student_medical_notes'),
        ('teachers', '0004_alter_teacherassignment_academic_year'),
        ('timetable', '0002_alter_timetableentry_academic_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcademicYear',
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['grade__order', 'name'], 'verbose_name': 'مادة دراسية', 'verbose_name_plural': 'المواد الدراسية'},
        ),
        migrations.AddField(
            model_name='enrollment',
            name='ended_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='academics.section'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='file',
            field=models.FileField(blank=True, upload_to='student_documents/'),
        ),
        migrations.AddField(
            model_name='studentlifecycleevent',
            name='from_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_events_from', to='academics.enrollment'),
        ),
        migrations.AddField(
            model_name='studentlifecycleevent',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_lifecycle_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentlifecycleevent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_events', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentlifecycleevent',
            name='to_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_events_to', to='academics.enrollment'),
        ),
    ]
