# Generated by Django 5.2.16 on 2026-07-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_delete_academicyear_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('transferred', 'منقول'), ('withdrawn', 'منسحب'), ('graduated', 'متخرج'), ('completed', 'مكتمل')], default='active', max_length=20),
        ),
    ]
