# Generated by Django 5.2.16 on 2026-07-12 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_alter_enrollment_status'),
        ('teachers', '0004_alter_teacherassignment_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='is_kindergarten',
            field=models.BooleanField(default=False, verbose_name='صف روضة'),
        ),
        migrations.AddField(
            model_name='section',
            name='homeroom_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_sections', to='teachers.teacher', verbose_name='مربي الصف'),
        ),
        migrations.AddField(
            model_name='section',
            name='is_default',
            field=models.BooleanField(default=False, help_text='تُستخدم عند عدم تقسيم الصف إلى أكثر من شعبة.', verbose_name='الشعبة الأساسية'),
        ),
    ]
