# Generated by Django 5.1.3 on 2026-06-27 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feecategory",
            old_name="default_amount",
            new_name="amount",
        ),
    ]
