# Generated by Django 5.1.3 on 2026-07-04 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_receipt"),
        ("students", "0004_student_national_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentinvoice",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="students.student",
            ),
        ),
    ]
