# Generated by Django 5.2.16 on 2026-07-11 18:00

import accounting.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def populate_finance_defaults(apps, schema_editor):
    StudentInvoice = apps.get_model("accounting", "StudentInvoice")
    for invoice in StudentInvoice.objects.all().iterator():
        invoice.invoice_number = f"INV-{invoice.pk:08d}"
        if invoice.paid:
            invoice.status = "paid"
        elif invoice.payments.exists():
            invoice.status = "partial"
        else:
            invoice.status = "open"
        invoice.save(update_fields=["invoice_number", "status"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_studentinvoice_student'),
        ('core', '0002_sequence'),
        ('students', '0005_student_is_active_student_medical_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=20)),
                ('decision_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'مستحق'), ('paid', 'مسدد'), ('overdue', 'متأخر'), ('cancelled', 'ملغى')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['due_date', 'sequence'],
            },
        ),
        migrations.AlterModelOptions(
            name='feecategory',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='studentinvoice',
            options={'ordering': ['-issue_date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='studentpayment',
            options={'ordering': ['-payment_date', '-id']},
        ),
        migrations.AddField(
            model_name='studentinvoice',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_invoices', to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='studentinvoice',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentinvoice',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentinvoice',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentinvoice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='studentinvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentinvoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='studentinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentinvoice',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='studentinvoice',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentinvoice',
            name='status',
            field=models.CharField(choices=[('open', 'مفتوحة'), ('partial', 'مدفوعة جزئيًا'), ('paid', 'مدفوعة'), ('cancelled', 'ملغاة')], db_index=True, default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='studentinvoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='reversal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='status',
            field=models.CharField(choices=[('posted', 'مرحلة'), ('reversed', 'معكوسة')], db_index=True, default='posted', max_length=20),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='accounting.studentpayment'),
        ),
        migrations.AlterField(
            model_name='studentinvoice',
            name='fee_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.feecategory'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounting.studentinvoice'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.RunPython(populate_finance_defaults, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='studentinvoice',
            name='invoice_number',
            field=models.CharField(default=accounting.models.new_invoice_number, editable=False, max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='studentinvoice',
            index=models.Index(fields=['status', 'due_date'], name='accounting__status_baf123_idx'),
        ),
        migrations.AddField(
            model_name='discountrequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_discounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discountrequest',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_requests', to='accounting.studentinvoice'),
        ),
        migrations.AddField(
            model_name='discountrequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_discounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='installment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='accounting.studentinvoice'),
        ),
        migrations.AlterUniqueTogether(
            name='installment',
            unique_together={('invoice', 'sequence')},
        ),
    ]
