# Generated by Django 5.2.16 on 2026-07-18 18:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_discountrequest_installment_and_more'),
        ('core', '0008_dataintegrityrun_school'),
        ('students', '0009_alter_student_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpayment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='deletion_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('card', 'بطاقة بنكية'), ('bank_transfer', 'تحويل بنكي'), ('online', 'دفع إلكتروني'), ('cheque', 'شيك'), ('unspecified', 'غير محدد (سجل سابق)')], db_index=True, default='unspecified', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='status',
            field=models.CharField(choices=[('posted', 'معتمدة'), ('deleted', 'محذوفة بأمان'), ('reversed', 'سجل سابق ملغى')], db_index=True, default='posted', max_length=20),
        ),
        migrations.CreateModel(
            name='ExpenseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_number', models.CharField(max_length=50, unique=True, verbose_name='رقم المصروف')),
                ('expense_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='تاريخ المصروف')),
                ('title', models.CharField(max_length=200, verbose_name='البيان')),
                ('beneficiary', models.CharField(blank=True, max_length=200, verbose_name='المستفيد')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('card', 'بطاقة بنكية'), ('bank_transfer', 'تحويل بنكي'), ('online', 'دفع إلكتروني'), ('cheque', 'شيك'), ('unspecified', 'غير محدد (سجل سابق)')], max_length=30, verbose_name='طريقة الدفع')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='المرجع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_expenses', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_entries', to='core.school')),
            ],
            options={
                'ordering': ['-expense_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FinancialYearClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_carried', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_year_closures', to='core.school')),
                ('source_year', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='financial_closure', to='core.academicyear')),
                ('target_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_financial_closures', to='core.academicyear')),
            ],
            options={
                'ordering': ['-closed_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialCarryForward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_carry_forwards', to='students.student')),
                ('target_invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='carry_forward_record', to='accounting.studentinvoice')),
                ('closure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='accounting.financialyearclosure')),
            ],
            options={
                'ordering': ['student__full_name'],
                'constraints': [models.UniqueConstraint(fields=('closure', 'student'), name='uniq_closure_student_balance')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyFinancialTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_end', models.DateField(db_index=True, verbose_name='نهاية الشهر المالي')),
                ('expected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ المتوقع شهريًا')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_financial_targets', to='core.school')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end'],
                'constraints': [models.UniqueConstraint(fields=('school', 'period_end'), name='uniq_monthly_target_school_period')],
            },
        ),
    ]
