# Generated by Django 5.2.16 on 2026-07-19 20:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_studentpayment_deleted_at_studentpayment_deleted_by_and_more'),
        ('core', '0008_dataintegrityrun_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseentry',
            name='invoice_file',
            field=models.FileField(blank=True, upload_to='finance/expense_invoices/', verbose_name='صورة الفاتورة'),
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='source',
            field=models.CharField(choices=[('school', 'مصروف مدرسي عام'), ('canteen', 'مصروف المقصف المدرسي')], db_index=True, default='school', max_length=20, verbose_name='مصدر المصروف'),
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='supplier_invoice_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='رقم فاتورة المورد'),
        ),
        migrations.CreateModel(
            name='CanteenTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'مبيعات المقصف'), ('expense', 'مصروف المقصف')], db_index=True, max_length=20, verbose_name='نوع الحركة')),
                ('transaction_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='التاريخ')),
                ('invoice_number', models.CharField(db_index=True, max_length=100, verbose_name='رقم الفاتورة')),
                ('description', models.CharField(max_length=200, verbose_name='البيان')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='القيمة')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('card', 'بطاقة بنكية'), ('bank_transfer', 'تحويل بنكي'), ('online', 'دفع إلكتروني'), ('cheque', 'شيك'), ('unspecified', 'غير محدد (سجل سابق)')], default='cash', max_length=30, verbose_name='طريقة الدفع')),
                ('invoice_file', models.FileField(blank=True, upload_to='finance/canteen_invoices/', verbose_name='صورة الفاتورة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_canteen_transactions', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_canteen_transactions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canteen_transactions', to='core.school')),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('school', 'invoice_number', 'transaction_type'), name='uniq_canteen_invoice_type')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyFinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_end', models.DateField(db_index=True, verbose_name='نهاية الشهر')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الرصيد المدور من الشهر السابق')),
                ('fee_income', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='وارد الرسوم')),
                ('canteen_income', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='وارد المقصف')),
                ('school_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المصروف المدرسي')),
                ('canteen_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مصروف المقصف')),
                ('net_movement', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='صافي حركة الشهر')),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الرصيد المدور للشهر التالي')),
                ('is_closed', models.BooleanField(db_index=True, default=False, verbose_name='مغلق')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_financial_statements', to='core.school')),
            ],
            options={
                'ordering': ['-period_end'],
                'constraints': [models.UniqueConstraint(fields=('school', 'period_end'), name='uniq_monthly_statement_school_period')],
            },
        ),
    ]
