# Generated by Django 5.1.4 on 2026-09-02 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0011_student_photo_size_limit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="رقم الهاتف"),
                ),
                (
                    "license_number",
                    models.CharField(max_length=50, verbose_name="رقم الرخصة"),
                ),
                (
                    "vehicle_details",
                    models.CharField(max_length=100, verbose_name="معلومات المركبة"),
                ),
                (
                    "is_active_driver",
                    models.BooleanField(default=True, verbose_name="سائق نشط"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransportRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم المسار")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routes",
                        to="transport.driverprofile",
                        verbose_name="السائق",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentTransportInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pickup_address",
                    models.TextField(blank=True, verbose_name="عنوان التواجد"),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="خط العرض"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="خط الطول"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعل")),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_info",
                        to="students.student",
                        verbose_name="الطالب",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="transport.transportroute",
                        verbose_name="المسار",
                    ),
                ),
            ],
        ),
    ]
