# Generated by Django 5.2.16 on 2026-09-02 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0013_delete_admissionapplication"),
        ("core", "0015_systemmobileapitoken"),
        ("parent_portal", "0014_alter_family_financial_policy_label"),
        ("transport", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransportDriver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="اسم السائق")),
                ("phone", models.CharField(max_length=30, verbose_name="رقم الهاتف")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transport_driver",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حساب النظام",
                    ),
                ),
            ],
            options={
                "verbose_name": "سائق مواصلات",
                "verbose_name_plural": "سائقو المواصلات",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TransportFamilyLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="وصف الموقع"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="العنوان")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="خط العرض",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="خط الطول",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "family",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_location",
                        to="parent_portal.family",
                        verbose_name="العائلة",
                    ),
                ),
            ],
            options={
                "verbose_name": "موقع مواصلات للعائلة",
                "verbose_name_plural": "مواقع مواصلات العائلات",
            },
        ),
        migrations.CreateModel(
            name="TransportGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_date", models.DateField(verbose_name="تاريخ التشغيل")),
                (
                    "direction",
                    models.CharField(
                        choices=[("morning", "ذهاب صباحي"), ("return", "عودة مسائية")],
                        max_length=20,
                        verbose_name="الاتجاه",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم المجموعة")),
                (
                    "max_students",
                    models.PositiveIntegerField(
                        default=10, verbose_name="الحد التقريبي للطلاب"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transport_groups",
                        to="admissions.transportroute",
                        verbose_name="المسار",
                    ),
                ),
            ],
            options={
                "verbose_name": "مجموعة مواصلات",
                "verbose_name_plural": "مجموعات المواصلات",
            },
        ),
        migrations.CreateModel(
            name="TransportTrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_date", models.DateField(verbose_name="تاريخ الرحلة")),
                (
                    "direction",
                    models.CharField(
                        choices=[("morning", "ذهاب صباحي"), ("return", "عودة مسائية")],
                        max_length=20,
                        verbose_name="الاتجاه",
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(default=1, verbose_name="رقم الرحلة"),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("car", "سيارة"),
                            ("bus", "حافلة"),
                            ("minibus", "باص صغير"),
                            ("coach", "باص كبير"),
                        ],
                        max_length=20,
                        verbose_name="نوع المركبة",
                    ),
                ),
                (
                    "vehicle_description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="وصف المركبة"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "مخططة"),
                            ("active", "نشطة"),
                            ("completed", "مكتملة"),
                            ("cancelled", "ملغاة"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الانطلاق"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الانتهاء"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trips",
                        to="transport.transportdriver",
                        verbose_name="السائق",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_trips",
                        to="admissions.transportroute",
                        verbose_name="المسار",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transport_trips",
                        to="core.school",
                        verbose_name="المدرسة",
                    ),
                ),
            ],
            options={
                "verbose_name": "رحلة مواصلات",
                "verbose_name_plural": "رحلات المواصلات",
                "ordering": ["service_date", "direction", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="TransportStudentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("arrived", "وصل إلى المحطة"),
                            ("boarded", "صعد إلى المركبة"),
                            ("dropped_off", "تم إنزاله"),
                            ("missed", "لم يصعد/لم يستلم"),
                        ],
                        max_length=20,
                        verbose_name="نوع الحدث",
                    ),
                ),
                ("occurred_at", models.DateTimeField(verbose_name="وقت الحدث")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transport_events",
                        to="admissions.studentregistration",
                        verbose_name="التسجيل",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_events",
                        to="transport.transporttrip",
                        verbose_name="الرحلة",
                    ),
                ),
            ],
            options={
                "verbose_name": "حدث مواصلات للطالب",
                "verbose_name_plural": "أحداث المواصلات للطلاب",
                "ordering": ["occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="TransportGPSPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="خط العرض"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="خط الطول"
                    ),
                ),
                (
                    "accuracy_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="دقة الموقع بالمتر",
                    ),
                ),
                (
                    "speed_kmh",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="السرعة كم/ساعة",
                    ),
                ),
                ("recorded_at", models.DateTimeField(verbose_name="وقت التسجيل")),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gps_points",
                        to="transport.transporttrip",
                        verbose_name="الرحلة",
                    ),
                ),
            ],
            options={
                "verbose_name": "نقطة GPS",
                "verbose_name_plural": "نقاط GPS",
                "ordering": ["recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="TransportAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transport_assignment",
                        to="admissions.studentregistration",
                        verbose_name="التسجيل",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_assignments",
                        to="transport.transportdriver",
                        verbose_name="السائق",
                    ),
                ),
                (
                    "morning_trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="morning_assignments",
                        to="transport.transporttrip",
                        verbose_name="رحلة الذهاب",
                    ),
                ),
                (
                    "return_trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_assignments",
                        to="transport.transporttrip",
                        verbose_name="رحلة العودة",
                    ),
                ),
            ],
            options={
                "verbose_name": "تكليف مواصلات",
                "verbose_name_plural": "تكليفات المواصلات",
            },
        ),
        migrations.CreateModel(
            name="TransportTripStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField(verbose_name="ترتيب المحطة")),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="اسم المحطة"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="العنوان")),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="خط العرض"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="خط الطول"
                    ),
                ),
                (
                    "arrived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الوصول"
                    ),
                ),
                (
                    "departed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت المغادرة"
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transport_trip_stops",
                        to="parent_portal.family",
                        verbose_name="العائلة",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="transport.transporttrip",
                        verbose_name="الرحلة",
                    ),
                ),
            ],
            options={
                "verbose_name": "محطة رحلة مواصلات",
                "verbose_name_plural": "محطات رحلات المواصلات",
                "ordering": ["trip", "sequence"],
            },
        ),
        migrations.AddIndex(
            model_name="transportdriver",
            index=models.Index(
                fields=["is_active", "name"], name="transport_t_is_acti_106a68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transportgroup",
            index=models.Index(
                fields=["route", "service_date", "direction"],
                name="transport_t_route_i_d829d4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transporttrip",
            index=models.Index(
                fields=["school", "service_date", "direction", "status"],
                name="transport_t_school__f6bd36_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transporttrip",
            index=models.Index(
                fields=["driver", "service_date", "direction"],
                name="transport_t_driver__fbc14a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="transporttrip",
            constraint=models.UniqueConstraint(
                fields=("driver", "service_date", "direction", "sequence"),
                name="uniq_transport_trip_driver_day_direction_seq",
            ),
        ),
        migrations.AddConstraint(
            model_name="transporttrip",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("driver",),
                name="uniq_active_transport_trip_per_driver",
            ),
        ),
        migrations.AddIndex(
            model_name="transportstudentevent",
            index=models.Index(
                fields=["trip", "registration", "occurred_at"],
                name="transport_t_trip_id_c2f1a7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transportstudentevent",
            index=models.Index(
                fields=["registration", "event_type"],
                name="transport_t_registr_d53db7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transportgpspoint",
            index=models.Index(
                fields=["trip", "recorded_at"], name="transport_t_trip_id_d41fdf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transportassignment",
            index=models.Index(
                fields=["driver", "is_active"], name="transport_t_driver__aec154_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transporttripstop",
            index=models.Index(
                fields=["trip", "sequence"], name="transport_t_trip_id_fa12a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transporttripstop",
            index=models.Index(
                fields=["family"], name="transport_t_family__463dd9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="transporttripstop",
            constraint=models.UniqueConstraint(
                fields=("trip", "sequence"), name="uniq_transport_stop_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="transporttripstop",
            constraint=models.UniqueConstraint(
                fields=("trip", "family"), name="uniq_transport_stop_family"
            ),
        ),
    ]
